export enum Role {
    ANONYMOUS="ANONYMOUS",
    AGENT="AGENT",
    MGA="MGA",
    RMD="RMD",
    MANAGER="MANAGER",
    PORTAL_ADMIN="PORTAL_ADMIN",
    USER_ADMIN="USER_ADMIN",
    STORE_ADMIN="STORE_ADMIN",
    CONTENT_ADMIN="CONTENT_ADMIN",
    REPORT_ADMIN="REPORT_ADMIN"
  }